### ISSUE TITLE
Remove top border on basic dropdown component when open

### ISSUE THREAD

**Issue by andykrier** [snewcomer/ember-power-select-mobile#1]
Subtle border-top on the `ember-basic-dropdown-content` div. I thought it was coming from our project, but I'm not seeing it there.  Maybe be a `power-select` default we just need to override.

**With border:**

<img width="378" alt="with-border" src="https://cloud.githubusercontent.com/assets/494195/18657881/30eb6528-7eb3-11e6-9a80-f2fd54b20e54.png">

**Without border:**

<img width="378" alt="without-border" src="https://cloud.githubusercontent.com/assets/494195/18657882/30ec0726-7eb3-11e6-82ad-53ae86453dfd.png">

**Effecting code:**

```css
.ember-power-select-dropdown.ember-basic-dropdown-content--above {
    border-top: 1px solid #E5E5E5; // this is the culprit
    border-bottom: none;
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
}
```
